version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-calander
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
